name: CI - Build & Publish

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write   # <-- required to push to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          COMMIT=ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker build -t "$IMAGE" -t "$COMMIT" .
          docker push "$IMAGE"
          docker push "$COMMIT"
