name: Deploy to VM (Docker)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy on remote Docker host
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          GHCR_IMAGE: ghcr.io/${{ github.repository }}:latest
          GHCR_USER: ${{ secrets.GHCR_USER }}
          GHCR_PAT:  ${{ secrets.GHCR_PAT }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          DB_URL: ${{ secrets.DB_URL }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        run: |
          ssh "$SSH_USER@$SSH_HOST" << 'EOF'
          set -e
          docker login ghcr.io -u "$GHCR_USER" -p "$GHCR_PAT"
          docker pull "$GHCR_IMAGE"

          docker stop mrbp-validate || true
          docker rm mrbp-validate || true

          docker run -d --name mrbp-validate --restart=always -p 8000:8000 \
            -e SESSION_SECRET="$SESSION_SECRET" \
            -e DB_URL="$DB_URL" \
            -e TENANT_ID="$TENANT_ID" \
            -e CLIENT_ID="$CLIENT_ID" \
            -e CLIENT_SECRET="$CLIENT_SECRET" \
            -e REDIRECT_URI="$REDIRECT_URI" \
            "$GHCR_IMAGE"
          EOF
