name: Deploy to VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add host
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker pull ghcr.io/${{ github.repository }}:latest
          docker stop mrbp-validate || true
          docker rm mrbp-validate || true
          docker run -d --name mrbp-validate -p 8000:8000 \
            -e SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            -e DB_URL=${{ secrets.DB_URL }} \
            ghcr.io/${{ github.repository }}:latest
          EOF
